languageCode: en-us
menu:
  main:
    - name: "<u>H</u>ome"
      url: /
      weight: 1
    - name: "<u>A</u>bout"
      url: /about/
      weight: 2
    - name: "<u>A</u>rchive"
      url: /archives/
      weight: 3
    - name: "<u>R</u>SS"
      url: /index.xml
      weight: 4
    - name: "<u>G</u>ithub"
      url: "https://github.com/rrx"
      weight: 5
    - name: "<u>L</u>inkedIn"
      url: "https://www.linkedin.com/in/ryansadler/"
      weight: 6
    - name: "<u>T</u>ags"
      url: "/tags"
      weight: 6

taxonomies:
  tag: tags

markup:
  highlight:
    codeFences: true
    style: bw
    lineNumbersInTable: false
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - html
    - rss
    - json
  page:
    - html

