name: github pages

on:
  push:
    branches:
      - main  # Set a branch that will trigger a deployment
      - generator
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: make install build
      - run: pwd
      - run: ls -la

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
